stages:
  - test

test-job:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - export INFLUX_URL="http://localhost:8086"
    - export INFLUX_TOKEN="test-token"
    - export INFLUX_ORG="test-org"
    - export INFLUX_BUCKET="test-bucket"
    - PYTHONPATH=hw6 pytest -v hw6/test_app.py